"""Synthetic interview simulator for offline evaluation.

The real system uses a closed-source LLM judge whose calls cost money and
have non-deterministic latency. To run controlled ablations we model both
the candidate and the LLM judge analytically:

    Candidate model (per category c):
        latent_ability θ_c ~ Beta(α_c, β_c)
        answer_quality on a question of difficulty d :
            q_t = clip( σ(k * (θ_c - d)) + noise, 0, 1 )

    Multi-judge LLM model (paper §4.1):
        for j = 1..J:
            judge_jt = clip( q_t + bias_j + ε_jt, 0, 1 )
        where ε_jt has heavier tails for low-quality answers (the place where
        real LLM judges actually disagree most). The ensemble's trimmed mean
        is what the experiment harness compares against true q_t.

    Question selection (paper §4.2):
        bandit policy chooses a category given memory features; the chosen
        category determines which θ_c drives the next answer.

Everything below is pure Python + numpy and is independent of the FastAPI
runtime so the experiment runner can sweep thousands of episodes quickly.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass, field
from typing import Any, Callable

import numpy as np

from app.agents.memory import (
    CATEGORIES,
    DIFFICULTY_MAP,
    label_difficulty,
    numeric_difficulty,
    update_after_eval,
)
from app.agents.state import InterviewState
from app.services.bandit import (
    ARMS,
    build_context,
    reward,
    select_category,
    update_after_reward,
)
from app.services.calibration import Calibrator, fit_platt
from app.services.difficulty import next_difficulty
from app.services.validator import REQUIRED_DIMENSIONS

RUBRIC_KEYS = REQUIRED_DIMENSIONS
RUBRIC_WEIGHTS = {
    "relevance": 0.18,
    "knowledge": 0.20,
    "specificity": 0.18,
    "reasoning": 0.16,
    "completeness": 0.14,
    "reflection": 0.08,
    "follow_up": 0.06,
}


# ---------------------------------------------------------------------------
# Candidate / judge models
# ---------------------------------------------------------------------------

@dataclass
class CandidateProfile:
    """Latent ability per category + a few global traits."""
    seed: int
    abilities: dict[str, float]           # category → θ_c ∈ [0,1]
    verbosity: float                      # how long-winded the candidate is
    resume_alignment: dict[str, float]    # per-category resume keyword hit

    def to_resume(self) -> dict:
        skills_pool = {
            "技术深度": ["Python", "算法原理", "性能优化"],
            "项目经验": ["项目经历", "上线落地"],
            "系统设计": ["分布式架构", "微服务", "可观测性"],
            "沟通表达": ["跨团队协作"],
            "学习能力": ["持续学习", "技术调研"],
        }
        skills: list[str] = []
        for cat, aff in self.resume_alignment.items():
            if aff > 0.5:
                skills += skills_pool.get(cat, [])[:2]
        return {
            "skills": skills,
            "projects": [{"name": "syn-project", "summary": "Synthetic candidate."}],
            "summary": "synthetic candidate profile generated by simulator.",
        }


def sample_candidate(rng: np.random.Generator, *, archetype: str = "balanced") -> CandidateProfile:
    """Generate a synthetic candidate.

    Real recruiting funnels are very skewed: most candidates are clearly
    stronger in 2-3 categories and visibly weaker in the others. We sample
    the strong-category set per archetype, then push those abilities up and
    the rest down so the bandit actually has a learnable signal.
    """
    if archetype == "junior":
        base = {c: rng.beta(2, 5) for c in CATEGORIES}
        strong = list(rng.choice(list(CATEGORIES), size=1, replace=False))
        verbosity = float(rng.uniform(0.6, 1.0))
    elif archetype == "senior":
        base = {c: float(np.clip(rng.beta(4, 3), 0.05, 0.95)) for c in CATEGORIES}
        strong = ["技术深度", "系统设计"] + list(rng.choice(["项目经验", "沟通表达", "学习能力"], size=1, replace=False))
        verbosity = float(rng.uniform(0.2, 0.5))
    elif archetype == "backend":
        base = {c: rng.beta(2, 4) for c in CATEGORIES}
        strong = ["技术深度", "系统设计"]
        verbosity = float(rng.uniform(0.3, 0.7))
    else:
        base = {c: rng.beta(2, 4) for c in CATEGORIES}
        strong = list(rng.choice(list(CATEGORIES), size=2, replace=False))
        verbosity = float(rng.uniform(0.3, 0.8))

    means: dict[str, float] = {}
    for c in CATEGORIES:
        if c in strong:
            means[c] = float(np.clip(base[c] + 0.35, 0.15, 0.95))
        else:
            means[c] = float(np.clip(base[c] - 0.15, 0.05, 0.5))

    # Resume alignment is informative: it correlates with strong categories.
    align: dict[str, float] = {}
    for c in CATEGORIES:
        if c in strong:
            align[c] = float(rng.beta(5, 2))
        else:
            align[c] = float(rng.beta(2, 5))

    return CandidateProfile(
        seed=int(rng.integers(0, 1_000_000)),
        abilities=means,
        verbosity=verbosity,
        resume_alignment=align,
    )


def simulate_answer_quality(
    cand: CandidateProfile,
    category: str,
    difficulty: float,
    *,
    rng: np.random.Generator,
    k: float = 5.0,
) -> float:
    """Latent ground-truth answer quality q ∈ [0,1]."""
    theta = cand.abilities[category]
    logit = k * (theta - float(difficulty))
    p = 1.0 / (1.0 + math.exp(-logit))
    noise = rng.normal(0, 0.05)
    return float(np.clip(p + noise, 0.0, 1.0))


@dataclass
class JudgePanel:
    """Ensemble of biased + noisy LLM judges."""
    biases: list[float]
    noise_scales: list[float]
    cot_bonus: bool                  # CoT → tighter noise

    def score(
        self,
        q: float,
        *,
        rng: np.random.Generator,
        outlier_trim: float,
    ) -> tuple[float, dict[str, list[float]], float]:
        """Return (aggregated_score_unit, per_dim_scores, agreement)."""
        per_dim: dict[str, list[float]] = {d: [] for d in RUBRIC_KEYS}
        for bias, scale in zip(self.biases, self.noise_scales):
            tail = scale * (1.6 if q < 0.3 else 1.0) * (0.7 if self.cot_bonus else 1.0)
            for d in RUBRIC_KEYS:
                # Different dimensions are slightly different views on q,
                # add a small dim-specific perturbation so cross-dim variance
                # isn't degenerate.
                dim_shift = rng.normal(0, 0.03)
                raw = q + bias + dim_shift + rng.normal(0, tail)
                per_dim[d].append(float(np.clip(raw, 0.0, 1.0) * 100.0))

        aggregated = {}
        for d, scores in per_dim.items():
            if outlier_trim > 0 and len(scores) >= 4:
                cut = int(len(scores) * outlier_trim)
                sliced = sorted(scores)[cut: len(scores) - cut] or scores
                aggregated[d] = sum(sliced) / len(sliced)
            else:
                aggregated[d] = sum(scores) / max(1, len(scores))

        score = sum(aggregated[d] * RUBRIC_WEIGHTS[d] for d in RUBRIC_KEYS)

        spreads = [max(per_dim[d]) - min(per_dim[d]) for d in RUBRIC_KEYS if len(per_dim[d]) > 1]
        mean_spread = sum(spreads) / max(1, len(spreads))
        agreement = max(0.0, 1.0 - mean_spread / 100.0)
        return float(score / 100.0), per_dim, agreement


def make_judge_panel(
    rng: np.random.Generator,
    *,
    j: int,
    use_cot: bool,
    base_noise: float = 0.18,
    panel_type: str = "homogeneous",
    n_adversaries: int | None = None,
) -> JudgePanel:
    """Sample a judge panel.

    ``panel_type`` controls how diverse the panel is:
      * ``homogeneous``    — small N(0, 0.05) biases, similar noise scales
        (matches the §4 narrative for a well-controlled multi-judge stack).
      * ``heterogeneous``  — larger biases (some judges over- or under-score),
        and noise scales are bimodal so 1-2 judges in the panel are notably
        less reliable than the rest. Exposes the failure mode that motivates
        RW-MJ in §6.
      * ``adversarial``    — a configurable number ``n_adversaries`` of
        judges are heavily biased + noisy (think: 'rogue' grader). Used by
        the adversary-fraction sweep in §6.

    ``n_adversaries`` only matters for ``adversarial``; when omitted in the
    ``heterogeneous`` regime the legacy "1 noisy + 1 moderately noisy"
    behaviour is preserved.
    """
    if panel_type == "heterogeneous":
        biases = list(rng.normal(0, 0.10, size=j))
        # Split into reliable (~base_noise) and unreliable (~base_noise * 2.5).
        scales = list(np.clip(rng.normal(base_noise, 0.04, size=j), 0.05, 0.4))
        if j >= 3:
            scales[0] = float(np.clip(base_noise * 2.5, 0.05, 0.5))   # one notably noisy
            biases[0] = float(np.clip(biases[0] + 0.18, -0.4, 0.4))    # and biased high
        if j >= 5:
            scales[1] = float(np.clip(base_noise * 1.8, 0.05, 0.5))    # one moderately noisy
    elif panel_type == "adversarial":
        n_adv = int(n_adversaries) if n_adversaries is not None else max(1, j // 2)
        n_adv = max(0, min(n_adv, j))
        biases = list(rng.normal(0, 0.05, size=j))
        scales = list(np.clip(rng.normal(base_noise, 0.04, size=j), 0.05, 0.4))
        # Alternate adversary biases between heavy-positive and heavy-negative
        # so the median anchor can't trivially recover the truth.
        for k in range(n_adv):
            sign = 1.0 if (k % 2 == 0) else -1.0
            biases[k] = float(np.clip(sign * 0.22, -0.4, 0.4))
            scales[k] = float(np.clip(base_noise * 2.8, 0.05, 0.5))
    else:
        biases = list(rng.normal(0, 0.05, size=j))
        scales = list(np.clip(rng.normal(base_noise, 0.04, size=j), 0.05, 0.4))
    return JudgePanel(biases=biases, noise_scales=scales, cot_bonus=use_cot)


# ---------------------------------------------------------------------------
# Episode loop — exercises the real bandit + memory + calibrator code paths.
# ---------------------------------------------------------------------------

@dataclass
class EpisodeConfig:
    strategy: str = "linucb"        # round_robin | linucb | thompson
    use_cot: bool = True
    judge_count: int = 1
    outlier_trim: float = 0.0
    calibrator: Calibrator | None = None
    difficulty_strategy: str = "pi_control"
    rounds: int = 12


@dataclass
class EpisodeTrace:
    cand: CandidateProfile
    rewards: list[float] = field(default_factory=list)
    arms: list[str] = field(default_factory=list)
    difficulties: list[float] = field(default_factory=list)
    raw_scores: list[float] = field(default_factory=list)   # judge ensemble output
    true_scores: list[float] = field(default_factory=list)  # ground-truth q
    calibrated_scores: list[float] = field(default_factory=list)
    agreements: list[float] = field(default_factory=list)
    ability_traj: list[float] = field(default_factory=list)
    coverage: list[dict[str, int]] = field(default_factory=list)

    def total_reward(self) -> float:
        return sum(self.rewards)

    def coverage_entropy(self) -> float:
        if not self.coverage:
            return 0.0
        last = self.coverage[-1]
        total = sum(last.values()) or 1
        H = 0.0
        for v in last.values():
            p = v / total
            if p > 0:
                H -= p * math.log(p)
        return H

    def calibration_mae(self) -> float:
        if not self.true_scores:
            return 0.0
        return float(np.mean(np.abs(np.array(self.true_scores) - np.array(self.calibrated_scores))))


def run_episode(
    cand: CandidateProfile,
    cfg: EpisodeConfig,
    *,
    rng: np.random.Generator,
    selector_override: Callable[[InterviewState, int, int], tuple[str, dict]] | None = None,
) -> EpisodeTrace:
    """One synthetic interview episode end-to-end."""
    panel = make_judge_panel(rng, j=cfg.judge_count, use_cot=cfg.use_cot)
    calibrator = cfg.calibrator or Calibrator()

    state: InterviewState = {
        "session_id": f"sim-{cand.seed}",
        "position": "AI Engineer",
        "difficulty": "mid",
        "resume_profile": cand.to_resume(),
        "question_plan": [],
        "qa_history": [],
        "target_total_questions": cfg.rounds,
        "ability_estimate": 0.5,
        "score_window": [],
        "per_topic_stats": {},
        "coverage_count": {},
        "gap_set": [],
        "next_direction_hints": [],
        "eval_provenance": [],
        "bandit_state": {},
        "difficulty_trajectory": [],
        "chapter_trajectory": [],
    }

    trace = EpisodeTrace(cand=cand)

    for t in range(1, cfg.rounds + 1):
        if selector_override is not None:
            chosen, sel_debug = selector_override(state, t, cfg.rounds)
        else:
            chosen, sel_debug = select_category(
                state,
                next_index=t,
                rounds_total=cfg.rounds,
                strategy=cfg.strategy,
            )
        diff_num, diff_label = next_difficulty(state)
        if cfg.difficulty_strategy == "heuristic":
            # Override difficulty controller: keep declared mid difficulty.
            diff_num = numeric_difficulty(state.get("difficulty") or "mid")
            diff_label = label_difficulty(diff_num)

        ctx = build_context(state, chosen, rounds_total=cfg.rounds)

        # 1) candidate answers
        q_true = simulate_answer_quality(cand, chosen, diff_num, rng=rng)

        # 2) LLM judges score it
        raw_unit, per_dim, agreement = panel.score(
            q_true, rng=rng, outlier_trim=cfg.outlier_trim,
        )

        # 3) calibration
        cal_unit = calibrator.apply(raw_unit, consensus=agreement if cfg.judge_count > 1 else None)

        # 4) memory + bandit updates (same code as production)
        mem_patch = update_after_eval(
            state,
            category=chosen,
            difficulty_numeric=diff_num,
            overall_score_unit=cal_unit,
            new_gaps=[],
            next_direction="",
            provenance=f"sim:t{t}:{chosen}",
        )
        state.update(mem_patch)

        # Same reward function for every strategy, so regret is apples-to-apples.
        cov_count = state.get("coverage_count") or {}
        cov_ratio = cov_count.get(chosen, 0) / max(1, sum(cov_count.values()) or 1)
        r_val = reward(
            overall_score_unit=cal_unit,
            target_difficulty=0.7,
            coverage_ratio=cov_ratio,
            gap_resolved=cal_unit > 0.5,
            resume_aff=cand.resume_alignment[chosen],
        )
        if cfg.strategy != "round_robin":
            state.update(update_after_reward(
                state,
                chosen_arm=chosen,
                context=ctx,
                reward_value=r_val,
                rounds_total=cfg.rounds,
            ))

        trace.rewards.append(r_val)
        trace.arms.append(chosen)
        trace.difficulties.append(diff_num)
        trace.raw_scores.append(raw_unit)
        trace.true_scores.append(q_true)
        trace.calibrated_scores.append(cal_unit)
        trace.agreements.append(agreement)
        trace.ability_traj.append(state.get("ability_estimate", 0.5))
        trace.coverage.append(dict(state.get("coverage_count") or {}))

    return trace


# ---------------------------------------------------------------------------
# Oracle baseline — knows true abilities; picks the arm that maximises the
# reward shaping function. Used to compute regret.
# ---------------------------------------------------------------------------

def oracle_selector(cand: CandidateProfile, target: float = 0.7) -> Callable[[InterviewState, int, int], tuple[str, dict]]:
    """Oracle: knows the true ability per category and picks the arm that
    maximises the *expected* shaped reward at the current memory state.

    We approximate E[q] by σ(k·(θ_c - d_c)) at the difficulty the production
    controller would pick (here we use the target as an upper-bound proxy).
    Together with the same coverage/resume terms used by the actor, this gives
    a fair, non-negative regret baseline.
    """
    from app.config import get_settings

    def _pick(state: InterviewState, next_index: int, rounds_total: int) -> tuple[str, dict]:
        s = get_settings()
        cov = state.get("coverage_count") or {}
        total = max(1, sum(cov.values()))
        best, best_score = ARMS[0], -1e9
        for arm in ARMS:
            theta = cand.abilities[arm]
            # Best-case expected answer quality at target difficulty.
            expected_q = 1.0 / (1.0 + math.exp(-5.0 * (theta - target)))
            cov_ratio = cov.get(arm, 0) / total
            cov_bonus = 1.0 - cov_ratio
            score = (
                1.0 * (1.0 - abs(expected_q - target))
                + s.bandit_lambda_coverage * cov_bonus
                + s.bandit_lambda_gap * (1.0 if expected_q > 0.5 else 0.0)
                + s.bandit_lambda_resume * cand.resume_alignment[arm]
            )
            if score > best_score:
                best, best_score = arm, score
        return best, {"strategy": "oracle"}

    return _pick


# ---------------------------------------------------------------------------
# Fit a calibrator from a held-out simulated pool. Used in the "with
# calibration" arm of the ablation table.
# ---------------------------------------------------------------------------

def fit_calibrator_from_pool(
    rng: np.random.Generator,
    *,
    n_candidates: int = 60,
    rounds: int = 10,
    judge_count: int = 3,
    use_cot: bool = True,
) -> Calibrator:
    raws: list[float] = []
    trues: list[float] = []
    for _ in range(n_candidates):
        cand = sample_candidate(rng, archetype=random.choice(["balanced", "backend", "junior", "senior"]))
        cfg = EpisodeConfig(
            strategy="round_robin",
            use_cot=use_cot,
            judge_count=judge_count,
            outlier_trim=0.15,
            rounds=rounds,
            calibrator=Calibrator(),
        )
        trace = run_episode(cand, cfg, rng=rng)
        raws.extend(trace.raw_scores)
        trues.extend(trace.true_scores)
    return fit_platt(raws, trues)
